# apps/interview/models/interview_session.py

import uuid

from django.conf import settings
from django.db import models
from django.utils import timezone

from apps.interview.choices import (
    DifficultyLevel,
    InterviewLevel,
    InterviewStatus,
    InterviewType,
)
from apps.interview.constants import (
    DEFAULT_INTERVIEW_DURATION,
    DEFAULT_TOTAL_QUESTIONS,
)


def resume_upload_path(instance, filename):
    return f"interviews/{instance.id}/resume/{filename}"


class InterviewSession(models.Model):
    """
    Stores interview configuration and candidate profile.

    Active interview state (questions, answers, feedback)
    is maintained in Redis.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    uploaded_file = models.FileField(
        upload_to=resume_upload_path
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="interview_sessions",
    )

    raw_content = models.TextField()

    candidate_profile = models.JSONField(
        default=dict
    )

    interview_type = models.CharField(
        max_length=20,
        choices=InterviewType.choices,
        default=InterviewType.TECHNICAL,
    )

    interview_level = models.CharField(
        max_length=20,
        choices=InterviewLevel.choices,
        default=InterviewLevel.JUNIOR,
    )

    difficulty = models.CharField(
        max_length=20,
        choices=DifficultyLevel.choices,
        default=DifficultyLevel.MEDIUM,
    )

    total_questions = models.PositiveSmallIntegerField(
        default=DEFAULT_TOTAL_QUESTIONS
    )

    duration_minutes = models.PositiveSmallIntegerField(
        default=DEFAULT_INTERVIEW_DURATION
    )

    status = models.CharField(
        max_length=20,
        choices=InterviewStatus.choices,
        default=InterviewStatus.CREATED,
    )

    started_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    completed_at = models.DateTimeField(
        null=True,
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        db_table = "interview_sessions"
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.id} ({self.status})"






class InterviewReport(models.Model):
    """
    Stores the final interview report.

    All detailed analytics generated by AI
    are stored inside report_json.
    """

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )

    interview_session = models.OneToOneField(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name="interview_report",
    )

    overall_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
    )

    report_json = models.JSONField()

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    class Meta:
        db_table = "interview_reports"
        ordering = ["-created_at"]

    def __str__(self):
        return f"Report - {self.interview_session_id}"


class InterviewState(models.Model):
    """
    Persists active interview websocket state between requests/processes.
    """

    conversation_id = models.UUIDField(
        primary_key=True,
        editable=False,
    )

    interview_session = models.ForeignKey(
        InterviewSession,
        on_delete=models.CASCADE,
        related_name="active_states",
    )

    state_json = models.JSONField()

    expires_at = models.DateTimeField(
        db_index=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True
    )

    updated_at = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        db_table = "interview_states"
        ordering = ["-updated_at"]

    @property
    def is_expired(self):
        return self.expires_at <= timezone.now()

    def __str__(self):
        return str(self.conversation_id)
