# Generated by Django 5.2.4 on 2026-07-22 07:41

import apps.interview.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file', models.FileField(upload_to=apps.interview.models.resume_upload_path)),
                ('raw_content', models.TextField()),
                ('candidate_profile', models.JSONField(default=dict)),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('mixed', 'Mixed'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Full Stack', 'Full Stack'), ('Data Engineer', 'Data Engineer')], default='technical', max_length=20)),
                ('interview_level', models.CharField(choices=[('fresher', 'Fresher'), ('junior', 'Junior'), ('Junior', 'Junior'), ('mid', 'Mid-Level'), ('Mid', 'Mid'), ('senior', 'Senior'), ('Senior', 'Senior')], default='junior', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('Easy', 'Easy'), ('medium', 'Medium'), ('Medium', 'Medium'), ('hard', 'Hard'), ('Hard', 'Hard')], default='medium', max_length=20)),
                ('total_questions', models.PositiveSmallIntegerField(default=10)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('report_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_report', to='interview.interviewsession')),
            ],
            options={
                'db_table': 'interview_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
