# Generated by Codex on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewState",
            fields=[
                (
                    "conversation_id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state_json", models.JSONField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_states",
                        to="interview.interviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "interview_states",
                "ordering": ["-updated_at"],
            },
        ),
    ]
